# Generated by Django 4.2.10 on 2024-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=32)),
                ('duration', models.CharField(max_length=32)),
                ('age_restriction', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='movies-images')),
            ],
        ),
    ]
