# Generated by Django 4.2.10 on 2024-02-23 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_of_rolling_date',
            field=models.DateField(default=datetime.date(2024, 2, 23)),
        ),
    ]
