# Generated by Django 4.2.10 on 2024-02-23 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_end_of_rolling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_of_rolling_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
