# Generated by Django 4.2.10 on 2024-03-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='film',
        ),
    ]
