# Generated by Django 4.2.10 on 2024-03-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_start_of_rolling_date'),
        ('tickets', '0002_remove_ticket_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
