# Generated by Django 4.2.10 on 2024-03-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='film',
        ),
    ]
